---
repos:
- repo: local
  hooks:
    - id: rustfmt
      name: rustfmt
      entry: rustfmt
      language: system
      files: "\\.rs$"
      args: ["--edition", "2024"]
    - id: leptosfmt
      name: leptosfmt
      entry: leptosfmt
      language: system
      files: "\\.rs$"
    - id: clippy
      name: clippy
      entry: cargo
      language: system
      files: "\\.rs$"
      pass_filenames: false
      args: ["clippy", "--fix", "--workspace", "--allow-dirty", "--allow-staged"]
