[package]
name = "twins-baby"
version = "0.1.0"
edition = "2024"

[workspace]

members = [
   "lib/cad-base", "lib/epsilon",
   "lib/solver"
]

[workspace.dependencies]
anyhow = "1.0"
approx = "0.5.1"
pretty_assertions = "1.4.1"
rstest = "0.26.1"
rand = "0.9.2"
ambassador = "0.5.0"
nom = "8.0.0"

[dependencies]
coarsetime = "0.1.36"
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.8", features = ["csr"] }
leptos-bevy-canvas = "0.4.0"


[dependencies.bevy]
version = "0.17.3"
features = [
    "bevy_mesh_picking_backend",
    "bevy_pbr",
    "bevy_picking",
    "bevy_window",
    "bevy_winit",
    "tonemapping_luts",
    "webgpu",
]

